#!/bin/sh
### BEGIN INIT INFO
# Provides:          
# Required-Start:    
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description:
# Description:       
#                    
#                    
#                    
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

do_start () {
	
	/root/hunrul/src/hunrul.sh
	echo "HUN jump inserted as INPUT first rule"
	iptables -I INPUT 1 -j HUN
}

do_stop () {
	iptables -D INPUT 1 
	echo "HUN jump deleted from INPUT chain"
}

do_status () {
	echo ""
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "You can only start. it just set of iptables rules..." >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: hunrul [start| ]" >&2
	exit 3
	;;
esac

:
